# StitcherBoy appveyor.yml script

branches:
  only:
    - master

version: '{branch}-{build}'
image: Visual Studio 2017

environment:
  NoTargetFrameworkNet35: true

install:
  - git submodule update --init --recursive

before_build:
  nuget restore

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

configuration: Release

build:
  parallel: true
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal
  project: StitcherBoy.sln

deploy:
  provider: NuGet
  api_key:
    secure: rEYnR9JThbc6x8DdCo1K8+fgsGKzjNKzTZsldXFLYMm/tFPC7JWWvuKpVTrDBd+g
  skip_symbols: false
